### PR TITLE
Add documentation structure

### PR DESCRIPTION
**Pull request by crisidev**
This implements the documentation structure of #16 

Once this is merged, we can push the docs to readthedocs and improve the API documentation through sphinx.

### CODE REVIEW

**Comment by crisidev** [comment]
Hum, tox for py27 is failing in teardown and setup of test cases like:

```
____ ERROR at setup of test_accounting_reply_unpack[!-follow-FOLLOW] _____
self = {'LANG': 'en_US.UTF-8', 'COV_CORE_SOURCE': 'tacacs_plus', 'COV_CORE_CONFIG': '', 'PYTHONHASHSEED': '3908957131', 'VIRT...usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'COV_CORE_DATAFILE': '/home/travis/build/crisidev/tacacs_plus/.coverage'}
key = 'PYTEST_CURRENT_TEST'
item = 'tests/test_tacacs_plus.py::test_accounting_reply_unpack[\x00\x00\x00\x00!\x00\x00-follow-FOLLOW] (setup)'
    def __setitem__(self, key, item):
>       putenv(key, item)
E       TypeError: must be string without null bytes, not str
.tox/py27/lib/python2.7/os.py:473: TypeError
___ ERROR at teardown of test_accounting_reply_unpack[!-follow-FOLLOW] ___
self = {'LANG': 'en_US.UTF-8', 'COV_CORE_SOURCE': 'tacacs_plus', 'COV_CORE_CONFIG': '', 'PYTHONHASHSEED': '3908957131', 'VIRT...usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'COV_CORE_DATAFILE': '/home/travis/build/crisidev/tacacs_plus/.coverage'}
key = 'PYTEST_CURRENT_TEST'
item = 'tests/test_tacacs_plus.py::test_accounting_reply_unpack[\x00\x00\x00\x00!\x00\x00-follow-FOLLOW] (teardown)'
    def __setitem__(self, key, item):
>       putenv(key, item)
E       TypeError: must be string without null bytes, not str
```

I honestly do not understand why...

**Comment by crisidev** [comment]
Ah, looks like to be related to pytest: https://github.com/pytest-dev/pytest/issues/2644

**Comment by ryanpetrello** [comment]
@crisidev thanks for spotting that, if you want to rebase, I've fixed the tests via https://github.com/ansible/tacacs_plus/commit/a2c86f5718496f903b1cb07db59927e92ec43260

**Comment by crisidev** [comment]
Yep! Will rebase and update.

**Pull request merged**
