### PR TITLE
Suggest that passwords be starred out for debug logs

### PR DESCRIPTION
**Pull request by spditner**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
This _is_ somewhat intentional :)

https://github.com/ansible/tacacs_plus/blob/bc626df7c81a08400e474211780a2fde56516ce9/bin/tacacs_client#L75

**Comment by spditner** [comment]
In my case, we weren't using the command line tool. The logging was being triggered via interaction with the TACACSClient object. I appreciate the desire to log things as they are in debug mode, however when logs are being scooped up by other systems for aggregation and analysis, I find I also desire the opposite :-P

**Comment by ryanpetrello** [comment]
To be honest, this is probably a result of this config option being poorly named.  Its original intent was really more as a tool for developing and analyzing the behavior of the library _itself_.  I think it makes sense to be more secure by default here, so this is probably a reasonable change to merge.

**Comment by ryanpetrello** [comment]
@spditner I've just released a new version of tacacs_plus on PyPI that includes this change:

https://pypi.org/project/tacacs_plus/2.5

**Pull request merged**
