### PR TITLE
Update package structure

### PR DESCRIPTION
**Pull request by crisidev**
Implement a more structured package. This is just code shuffled around, not changes in the implementation.

This is the first part of https://github.com/ansible/tacacs_plus/issues/11

Code is not structured as below:
```
tac_plus/__init__.py - version and global constanst
tac_plus/flags.py - all the protocol flags
tac_plus/packet.py - packet object and helpers
tac_plus/authentication.py - authentication object and helpers
tac_plus/authorisation.py - authorisation object and helpers
tac_plus/accounting.py - accounting object and helpers
tac_plus/aaa.py - send and receive methods, using object from above files
tests/test_tac_plus.py - tests, to be compliant with pytest and usable with python setup.py test
```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
@crisidev this looks great - thanks for putting in the work to reorganize this.  My only minor comment is that I think a better name for `aaa.py` would be `client.py`

**Comment by crisidev** [comment]
Fair enough. I'll update the name. Once this is merged, I have the accounting part more or less done.

I am also adding testing for author and accounting. Do you prefer the testing in a PR separate from accounting one?

**Comment by ryanpetrello** [comment]
@crisidev that's awesome - thanks for doing that :D

I'm fine w/ the tests for authorization going in a joint PR.

**Comment by ryanpetrello** [comment]
@crisidev I squashed this and merged it via #13

**Pull request closed without merging**
